spring:
  application:
    name: chatbotapi

  datasource:
    url: jdbc:mysql://localhost:8002/chatbot?serverTimezone=Asia/Seoul
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: create # 기존 'create'를 변경했으나 필요에 따라 수정
    show-sql: true

server:
  port: 8001

jwt:
  secret-key: 4Ixa3PT4KhLW1fz4bJoY8z2dR4Gk7jHpB3Yw8mQvL9NdXx5vT9Yw8VhN3rB4YxK2

llm:
  url: http://ec2-13-208-253-99.ap-northeast-3.compute.amazonaws.com:8000